
import React from "react";
import Intro from "./_components/intro";
import Footer from "./_components/footer";
import ScrollToTopButton from "./_components/ScrollToTopButton";
import './globals.css';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <Intro />
        </header>
        {children}
        <Footer />
        <ScrollToTopButton /> {/* Adiciona o botão de voltar ao topo */}
      </body>
    </html>
  );
}
