import React from "react";
import Intro from "./_components/intro";
import Footer from "./_components/footer";
import './globals.css';
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="">
          <Intro />
        </header>
        {children}
      </body>
      <Footer />
    </html>
  );
}
